const mongoose = require('mongoose')
const infoChampSchema=mongoose.Schema({
    key:{
        type:Number,
        require:true
    },
    name:{
        type:String,
        require:true
    },
    title:{
        type:String,
        require:true
    },
    image:{
        type:Array,
        require:true
    },
    skin:{
        type:Array,
        require:true
    },
    lore:{
        type:String,
        require:true
    },
    blurb:{
        type:String,
        require:true
    },
    allytips:{
        type:Array,
        require:true
    },
    enemytips:{
        type:Array,
        require:true
    },
    tags:{
        type:Array,
        require:true
    },
    partype:{
        type:String,
        require:true
    },
    info:{
        type:Object,
        require:true
    },
    stats:{
        type:Object,
        require:true
    },
    spells:{
        type:Array,
        require:true
    },
    passive:{
        type:Object,
        require:true
    },

}) 